# _____        ___                    ___                    _
#/__   \__ _  / __\___  _ __  _ __   / _ \_ __ ___ _ __ ___ (_)_   _ _ __ ___
#  / /\/ _` |/ /  / _ \| '_ \| '_ \ / /_)/ '__/ _ \ '_ ` _ \| | | | | '_ ` _ \
# / / | (_| / /__| (_) | | | | | | / ___/| | |  __/ | | | | | | |_| | | | | | |
# \/   \__, \____/\___/|_| |_|_| |_\/    |_|  \___|_| |_| |_|_|\__,_|_| |_| |_|
#      |___/

licenseKey: "" #If you don't have one contact @Lorenzo137 on Telegram to get one!

serverIdentifier: "server" #This will have to be the prefix of all telegram commands and will identify your server in the notifications.

botToken: ""
# Bot token provided by BotFather

ownerChatId: 0
# Your userID (follow the guide on Spigot to understand how to find it)

findChatId: false
# It allows you to see the userID of the person who is writing to the bot (follow the guide to understand how it works)

#ChatIDs :
# - The chats where the bot will send the notification messages.
# - The chats where the bot will listen for commands.

ChatIDs:
  - 0
AdminIDs:
  - 0

#AdminIDs:
# - Admins that will hold the power to execute commands.

tg_messages:  #By leaving the messages blank you disable them.
  serverStarted: "[%server%] ğŸŸ¢ Server is online! "
  serverStopped: "[%server%] ğŸ”´ Server went offline! "
  playerJoined: "[%server%] â• <b>%player%</b>"
  playerLeft: "[%server%] â– <b>%player%</b>"
  playerDeath: "[%server%] %player% died. ğŸ’€"  #You can use %deathMessage%, it will take the death message; or %player% for the player's name
  playerAdvancementDoneEvent: "[%server%] %player% completed [<b>%advancement%</b>]! ğŸ†"
  playerCommand: "[%server%] ğŸ’» <b>%player%</b> : <code>%command%</code>"
  playerChat: "[%server%] <b>%player%</b> : %message%"
  playerKick: "[%server%] ğŸš© <b>Kick Event</b>\n<b>Player</b>: %player%\n<b>Reason</b>: %reason%"

customCommands:
  1:
    invocation: "test"
    commands:
      - "say Hello Guys!"
      - "say This is just a Test!"
  2:
    invocation: "op"
    commands:
      - "op %arg1%"